### ISSUE TITLE
Cannot send message: status 500: 411 Length Required

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain#247]
**Describe the bug**
When I try to send a message on mainnet or testnets, I receive the following error from the mailchain client:

```
ERRO[2019-09-04T23:14:59+01:00] status 500: 411 Length Required <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>411 Length Required</title>
</head><body>
<h1>Length Required</h1>
<p>A request of the requested method POST requires a valid Content-length.<br />
</p>
</body></html>
could not determine chain id
could not send transaction
could not send message
```
The api url is: https://inbox.mailchain.xyz/api/ethereum/ropsten/messages/send

**To Reproduce**

Start the mailchain client
1. Go to 'inbox.mailchain.xyz'
1. Click on 'compose'
1. Compose a message
1. Click send
1. See error on console output

**What version of Mailchain are you using ?**
$ mailchain version
Version: v0.0.32

**Expected behavior**
The message should send and there should be no console output

**Desktop (please complete the following information):**

OS: iOS
Browser chrome

**Comment by tboeckmann** [comment]
Appears to be related to response from Alchemy.
Will keep an eye out for similar issues.

**Comment by robdefeo** [comment]
This root cause of this issue is due to the `content-length` header being dropped by the proxy, which ordinarily would not be a problem when creating a new request as the length is obtained from the reader. However since the reader is not accessed the length is not set. This needs to be explicitly set. See https://deliveroo.engineering/2019/02/22/go-down-the-rabbit-hole.html for an example
