### ISSUE TITLE
Use protocol & network to calculate public address from public key 

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#271]
**Is your feature request related to a problem? Please describe.**
substrate has a different prefix for addresses dependant on the network. Currently the `Address() []byte` does not allow for passing in the network parameter.

**Describe the solution you'd like**
```
// PublicKey definition usable in all mailchain crypto operations
type PublicKey interface {
	// Bytes returns the byte representation of the public key
	Bytes() []byte
	// Address returns the byte representation of the address
	Address(protocol, network string) []byte
}
```
This can be ignored for networks that don't have this feature

**Describe alternatives you've considered**

**Additional context**
In the case that a different key type is used than that or the network, this needs to be handled in someway, as public key / private key is not relevant anymore.

**Comment by robdefeo** [comment]
One side effect of doing this is adding a private key to the keystore. Currently either the curve type or protocol is supplied as a parameter.
```
Usage:
  mailchain account add [flags]

Flags:
  -C, --chain string         Select the chain [ethereum]
  -h, --help                 help for add
      --passphrase string    Passphrase to encrypt/decrypt key with
  -K, --private-key string   Specify the private key to store

Global Flags:
      --config string         config file (default is $HOME/.mailchain/.mailchain.yaml)
      --empty-passphrase      no passphrase and no prompt
      --key-type string       Select the chain [secp256k1]
      --log-level string      log level [Panic,Fatal,Error,Warn,Info,Debug] (default "warn")
      --prevent-init-config   stop automatically creating config if non is found
```
Requiring the protocol and network to generate address breaks this. 
1. Should add key mean that you must specify protocol and address? 
1. What about if there is no different generation address based on network. E.g. ethereum
1. What about `curve-type` where same key can be used in multiple protocols.

**Comment by robdefeo** [comment]
One option to address question 2 would be to have `--network` as optional and if empty add for each network.

**Comment by tboeckmann** [comment]
Looking at how substrate's `subkey` in https://substrate.dev/docs/en/ecosystem/subkey#inspecting-keys, the optional `--network` flag is used.

I'd prefer to see `network` broken out into its own object and instead add a familiar name flag (`--name`). Here's why:

In Ethereum, if I want to use a different network:
The same private key always derives the same public key and public address.

In substrate, if I want to use a different network:
The same private key always derives the same public key but for each different network, the public address changes (the network ID added as first byte and hash of network ID and public key as last 2 bytes, then it is encoded).

In either Ethereum or Substrate, the `network` is only relevant when public address is used (in transactions, querying public addresses for messages, etc.), which can be generated from the `/protocols` endpoint and iterating through networks if relevant (see #281).

**Should add key mean that you must specify protocol and address?**

No. I don't think you'd add address because this is derived from the private key.
Simply `protocol` (once #279 is closed).

**What about if there is no different generation address based on network. E.g. ethereum**

See above- I think that's addressed.

**What about curve-type where same key can be used in multiple protocols.**

There are 2 approaches here we could consider (and even support both):
1) Make protocol declaration explicit, so if you want to use a different protocol or a network that runs on a protocol, you need to declare this. _This would require adding some way to configure/ store the protocols and networks a user has declared_
This makes sense because users decide what to work with.

2) Include the majority of mainstream protocols and their networks automatically. This saves a user from needing to manually add all forks, airdrops or other networks that they may not know about. It could lead to confusion and overhead to query unused networks. Also, who will maintain the list of all these networks and the nodes to query for messages? Who decides which networks should be supported? Seems like a never ending and contentious road.

    Option 1 seems like a better approach for now.

**Comment by robdefeo** [comment]
Thanks for the clarification @tboeckmann . Apologies though there was a mistake in question 1

> Should add key mean that you must specify protocol and address?
**address** was a typo, it should of been network. Currently the private keys are stored as individually with the ID being the address. Due to needing the network to calculate the address in polkadot this is why one proposal is to request it when adding the key. Another is to look for another suitable, not that one comes to mind right now.

**Comment by tboeckmann** [comment]
@robdefeo Ok- that makes sense as to why you'd want to know the network. In the case of substrate, you might just go with public key (or a base58 encoded pub_key to shorten it). It's a starting point that can be used in the application to determine where it came from.
