### ISSUE TITLE
Add verify method to ed25519.PublicKey 

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#346]
**Is your feature request related to a problem? Please describe.**
It is not possible to verify if a `[]byte` is signed by a public key.  This is a problem, when determining the public key from an address and there are multiple different public key possibilities due to the protocol allowing different key types.

**Describe the solution you'd like**
Implement `Verify(message, sig []byte) bool ` on `ed25519.PublicKey`. Use `ed25519test` package to test signed messages with both `sofia` and `charlotte` keys. This will mean that the validity of the signed data against this public key / key type can be verified.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Despire** [comment]
I would like to work on this. However I'm not quite sure how to exactly verify the `[]byte`.

I assume that the `[]byte` passed to `Verify` are data encrypted via [nacl.Encrypter](https://github.com/mailchain/mailchain/blob/master/crypto/cipher/nacl/encrypter.go#L29), so it contains the `nonce` and `ciphertext`. I thought of decrypting via [secretbox.Open](https://github.com/golang/crypto/blob/HEAD/nacl/secretbox/secretbox.go#L125) however that wouldn't work since the private key would be needed. Maybe a check against some hash would be needed ? 
I would appreciate a hint. @robdefeo

**Comment by robdefeo** [comment]
@Despire signed data can be verified. You are correct in identifying that encrypted data is not compatible with the verify method. I have just created #373 which would be easier to work on first then, the result of the `Sign` can be used here. @Despire let me know if you would like to work on that first otherwise I will generate some test data for you.

**Comment by Despire** [comment]
Yes I can work on that too

**Comment by Despire** [comment]
@robdefeo so the `data []byte` passed to the `Verify` method contains both the signature and the message right ?

**Comment by robdefeo** [comment]
Closed in error.

**Comment by robdefeo** [comment]
@Despire I have updated the issues as the `Verify` func as you have identified is missing something `Verify(message, sig []byte) bool ` there the message, and the signature. Hope this helps

**Comment by robdefeo** [comment]
closed by #400 thanks @Despire
